[package]
org = "niveathika"
name = "pluralize"
version = "1.0.1"
authors = ["Niveathika"]
keywords = ["Plural", "Pluralize", "Singular", "Singularize"]
repository = "https://github.com/ballerina-platform/module-niveathika-pluralize"
license = ["Apache-2.0"]
distribution = "2201.9.0"

[build-options]
observabilityIncluded = true